import type { Component } from 'vue'
import { ArrowDownUp, ListChecks, BookOpen, Users, Calculator, Globe } from 'lucide-vue-next'
import type { ComponentStory } from './types/story'

// Navigation source of truth. The sidebar reads these arrays; the /apps/:slug and
// /component/:slug hosts resolve a slug back to an entry here.
//
//   apps       — full, composed app demos. Explicit list below (no props/variants).
//   components — reusable components in isolation. AUTO-DISCOVERED from co-located
//                `*.story.ts` files: drop a story beside a component and it appears
//                in the catalog. You do not edit this file to add a component.

export interface AppEntry {
  slug: string
  title: string
  icon: Component
  component: () => Promise<Component>
}

// A resolved component entry = its story plus a guaranteed slug.
export interface ComponentEntry extends ComponentStory {
  slug: string
}

// ---- Full app demos: composed, stateful, the real thing running ----
export const apps: AppEntry[] = [
  { slug: 'product-sort', title: 'Product Sort', icon: ArrowDownUp, component: () => import('./views/ProductSort.vue') },
  { slug: 'tasks', title: 'Tasks', icon: ListChecks, component: () => import('./views/Tasks.vue') },
  { slug: 'books', title: 'Books', icon: BookOpen, component: () => import('./views/Dashboard.vue') },
  { slug: 'users', title: 'Users', icon: Users, component: () => import('./views/UserList.vue') },
  { slug: 'counter', title: 'Counter', icon: Calculator, component: () => import('./views/Counter.vue') },
  { slug: 'hello', title: 'Hello World', icon: Globe, component: () => import('./views/HelloWorld.vue') },
]

// "UserCard.story.ts" -> "user-card"
function slugFromPath(path: string): string {
  const file = path.split('/').pop()!.replace(/\.story\.ts$/, '')
  return file.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
}

// ---- Reusable components: every co-located *.story.ts, discovered at build time ----
const storyModules = import.meta.glob<{ default: ComponentStory }>(
  './components/**/*.story.ts',
  { eager: true },
)

export const components: ComponentEntry[] = Object.entries(storyModules)
  .map(([path, mod]) => ({ ...mod.default, slug: mod.default.slug ?? slugFromPath(path) }))
  .sort((a, b) => a.title.localeCompare(b.title))

export const findApp = (slug: string): AppEntry | undefined => apps.find((a) => a.slug === slug)
export const findComponent = (slug: string): ComponentEntry | undefined =>
  components.find((c) => c.slug === slug)
